name = "prayer-times-api"
main = "src/index.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_NAME = "prayer-times"
APP_VERSION = "0.1.0"

# ✅ اسم مستخدم GitHub الحقيقي هنا
# - الأول: للـ Live Server المحلي
# - الثاني: لموقع GitHub Pages: https://yassinehmd67.github.io/prayer-times/
CORS_ALLOWED_ORIGINS = "http://127.0.0.1:5500,https://yassinehmd67.github.io"

CACHE_TTL_SHORT = "3600"
CACHE_TTL_LONG = "21600"
DEFAULT_PRO_QUOTA = "50000"

[[kv_namespaces]]
binding = "PRAYER_KV"
id = "0fdfe9c4c73c46b5864bdfe5aebe2bd9"
